baseURL = "https://practice-member.github.io/nandemo-output-blog/"
languageCode = "ja-JP"
title = "或いはバグでいっぱいのコード"
theme = "liva-hugo"
summaryLength = "3"
paginate = 6
disqusShortname = ""
publishDir = "docs"

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2


  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2




#################### default parameters ################################
[params]
logo = "images/blog_test_logo.png"
home = "Home"
# Meta data
description = "学んだことを何でもアウトプットするためのブログ"
author = "Practice Members"
# Google Analitycs
googleAnalitycsID = "Your ID"
# copyright
copyright = "| copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true



############################# social site ########################

[[params.social]]
title = ""
icon = "" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = ""
icon = "" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = ""
icon = "" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/practice-member/nandemo-output-blog"

[[params.social]]
title = ""
icon = "" # themify icon : https://themify.me/themify-icons
link = "#"

